// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package openapi

import (
	externalRef0 "github.com/unikorn-cloud/core/pkg/openapi"
)

const (
	Oauth2AuthenticationScopes = "oauth2Authentication.Scopes"
)

// BaremetalClusterRead Baremetal cluster read.
type BaremetalClusterRead struct {
	Metadata externalRef0.ProjectScopedResourceReadMetadata `json:"metadata"`

	// Spec Baremetal cluster creation parameters.
	Spec BaremetalClusterSpec `json:"spec"`
}

// BaremetalClusterSpec Baremetal cluster creation parameters.
type BaremetalClusterSpec struct {
	// RegionId The region to provision the cluster in.
	RegionId string `json:"regionId"`

	// WorkloadPools A list of Baremetal cluster workload pools.
	WorkloadPools BaremetalClusterWorkloadPools `json:"workloadPools"`
}

// BaremetalClusterWorkloadPool A Kuberntes cluster workload pool.
type BaremetalClusterWorkloadPool struct {
	// Machine A Baremetal cluster machine.
	Machine MachinePool `json:"machine"`

	// Name Workload pool name.
	Name string `json:"name"`
}

// BaremetalClusterWorkloadPools A list of Baremetal cluster workload pools.
type BaremetalClusterWorkloadPools = []BaremetalClusterWorkloadPool

// BaremetalClusterWrite Baremetal cluster create or update.
type BaremetalClusterWrite struct {
	// Metadata Resource metadata valid for all API resource reads and writes.
	Metadata externalRef0.ResourceWriteMetadata `json:"metadata"`

	// Spec Baremetal cluster creation parameters.
	Spec BaremetalClusterSpec `json:"spec"`
}

// BaremetalClusters A list of Baremetal clusters.
type BaremetalClusters = []BaremetalClusterRead

// BaremetalNameParameter A Baremetal name. Must be a valid DNS containing only lower case characters, numbers or hyphens, start and end with a character or number, and be at most 63 characters in length.
type BaremetalNameParameter = string

// MachinePool A Baremetal cluster machine.
type MachinePool struct {
	// FlavorId Flavor ID.
	FlavorId *string `json:"flavorId,omitempty"`

	// Replicas Number of machines for a statically sized pool or the maximum for an auto-scaled pool.
	Replicas *int `json:"replicas,omitempty"`
}

// ClusterIDParameter A Baremetal name. Must be a valid DNS containing only lower case characters, numbers or hyphens, start and end with a character or number, and be at most 63 characters in length.
type ClusterIDParameter = BaremetalNameParameter

// OrganizationIDParameter A Baremetal name. Must be a valid DNS containing only lower case characters, numbers or hyphens, start and end with a character or number, and be at most 63 characters in length.
type OrganizationIDParameter = BaremetalNameParameter

// ProjectIDParameter A Baremetal name. Must be a valid DNS containing only lower case characters, numbers or hyphens, start and end with a character or number, and be at most 63 characters in length.
type ProjectIDParameter = BaremetalNameParameter

// BaremetalClusterResponse Baremetal cluster read.
type BaremetalClusterResponse = BaremetalClusterRead

// BaremetalClustersResponse A list of Baremetal clusters.
type BaremetalClustersResponse = BaremetalClusters

// CreateBaremetalClusterRequest Baremetal cluster create or update.
type CreateBaremetalClusterRequest = BaremetalClusterWrite

// PostApiV1OrganizationsOrganizationIDProjectsProjectIDClustersJSONRequestBody defines body for PostApiV1OrganizationsOrganizationIDProjectsProjectIDClusters for application/json ContentType.
type PostApiV1OrganizationsOrganizationIDProjectsProjectIDClustersJSONRequestBody = BaremetalClusterWrite

// PutApiV1OrganizationsOrganizationIDProjectsProjectIDClustersClusterIDJSONRequestBody defines body for PutApiV1OrganizationsOrganizationIDProjectsProjectIDClustersClusterID for application/json ContentType.
type PutApiV1OrganizationsOrganizationIDProjectsProjectIDClustersClusterIDJSONRequestBody = BaremetalClusterWrite
