//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 the Unikorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	unikornv1alpha1 "github.com/unikorn-cloud/core/pkg/apis/unikorn/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalCluster) DeepCopyInto(out *BaremetalCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalCluster.
func (in *BaremetalCluster) DeepCopy() *BaremetalCluster {
	if in == nil {
		return nil
	}
	out := new(BaremetalCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BaremetalCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalClusterList) DeepCopyInto(out *BaremetalClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BaremetalCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalClusterList.
func (in *BaremetalClusterList) DeepCopy() *BaremetalClusterList {
	if in == nil {
		return nil
	}
	out := new(BaremetalClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BaremetalClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalClusterSpec) DeepCopyInto(out *BaremetalClusterSpec) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(unikornv1alpha1.NetworkGeneric)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadPools != nil {
		in, out := &in.WorkloadPools, &out.WorkloadPools
		*out = new(BaremetalClusterWorkloadPoolsSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalClusterSpec.
func (in *BaremetalClusterSpec) DeepCopy() *BaremetalClusterSpec {
	if in == nil {
		return nil
	}
	out := new(BaremetalClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalClusterStatus) DeepCopyInto(out *BaremetalClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]unikornv1alpha1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalClusterStatus.
func (in *BaremetalClusterStatus) DeepCopy() *BaremetalClusterStatus {
	if in == nil {
		return nil
	}
	out := new(BaremetalClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalClusterWorkloadPoolsPoolSpec) DeepCopyInto(out *BaremetalClusterWorkloadPoolsPoolSpec) {
	*out = *in
	in.BaremetalWorkloadPoolSpec.DeepCopyInto(&out.BaremetalWorkloadPoolSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalClusterWorkloadPoolsPoolSpec.
func (in *BaremetalClusterWorkloadPoolsPoolSpec) DeepCopy() *BaremetalClusterWorkloadPoolsPoolSpec {
	if in == nil {
		return nil
	}
	out := new(BaremetalClusterWorkloadPoolsPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalClusterWorkloadPoolsSpec) DeepCopyInto(out *BaremetalClusterWorkloadPoolsSpec) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]BaremetalClusterWorkloadPoolsPoolSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalClusterWorkloadPoolsSpec.
func (in *BaremetalClusterWorkloadPoolsSpec) DeepCopy() *BaremetalClusterWorkloadPoolsSpec {
	if in == nil {
		return nil
	}
	out := new(BaremetalClusterWorkloadPoolsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaremetalWorkloadPoolSpec) DeepCopyInto(out *BaremetalWorkloadPoolSpec) {
	*out = *in
	in.MachineGeneric.DeepCopyInto(&out.MachineGeneric)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaremetalWorkloadPoolSpec.
func (in *BaremetalWorkloadPoolSpec) DeepCopy() *BaremetalWorkloadPoolSpec {
	if in == nil {
		return nil
	}
	out := new(BaremetalWorkloadPoolSpec)
	in.DeepCopyInto(out)
	return out
}
